### ISSUE TITLE
Support for ARM64 architecture

### ISSUE THREAD

**Issue by semaf** [SamuelTallet/MongoDB-PHP-GUI#34]
Hey,

Arm64 is not supported over docker. Will you add it?

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by SamuelTallet** [comment]
Hello. ARM 64... Why not? 🙂 Do you know how?

**Comment by patrickdk77** [comment]
i already do on my branch. didnt realize this didnt. ill commit a pr when i get home tomorrow

**Comment by SamuelTallet** [comment]
@patrickdk77 Great!

**Comment by SamuelTallet** [comment]
@semaf Since MongoDB PHP GUI v1.3.1, ARM64 arch is supported. Please pull Docker image again.
