### ISSUE TITLE
How to query ObjectId with this?

### ISSUE THREAD

**Issue by aldokkani** [SamuelTallet/MongoDB-PHP-GUI#39]
I cannot query based on objectId in this thing.
{key: "\<id\>"} doesn't work
{key: ObjectId("\<id\>")} doesn't work either!

**Comment by SamuelTallet** [comment]
Let `ObjectId("6f358e03c3360000ef0076d4")`, you can query with

```js
_id: "6f358e03c3360000ef0076d4"
```

or

**Comment by SamuelTallet** [comment]
Let `ObjectId("6f358e03c3360000ef0076d4")`, you can query with:

```
{ _id: "6f358e03c3360000ef0076d4" }
```
or

```
_id: "6f358e03c3360000ef0076d4"
```

**Comment by aldokkani** [comment]
The key in my case is "definitionId" it is not the `_id` and no this doesn't work
{definitionId: "someid"}

**Comment by SamuelTallet** [comment]
Ah! That's why! 😉 Only ObjectId fields named `_id` are supported by MongoDB PHP GUI for now.
